learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'users/',include('users.urls',namespace='users')),
	url(r'',include('learning_logs.urls',namespace='learning_logs'))
]	

learning_logs/urls.py
#coding:utf-8
"""定义learning_logs的URL Patterns"""
from django.conf.urls import url
from . import views

urlpatterns = [
	#主页
	url(r'^$',views.index,name='index'),
	#实现所有的主题
	url(r'^topics/$',views.topics,name='topics'),
	#实现主题下某个标题
	url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
	#实现添加主题
	url(r'^new_topic/$',views.new_topic,name='new_topic'),
	#删除主题
	url(r'^del_topic/(?P<topic_id>\d+)/$',views.del_topic,name='del_topic'),
	#实现添加条目
	url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
	#实现编辑条目
	url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name="edit_entry")
]

users/urls.py
#coding:utf-8
"""定义learning_logs的URL Patterns"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views


urlpatterns = [
	#用户登录
	url(r'^login',login,{'template_name':'users/login.html'},name='login'),
	#用户退出
	url(r'^logout',views.logout_view,name='logout'),
	#用户注册
	url(r"^register/$",views.register,name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User #引用django的登录用户，这个是django默认的用户models


# Create your models here.
class Topic(models.Model):
	"""用户学习的主题"""
	text=models.CharField(max_length=200)
	date_added=models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User) #创建关联表与Django的登录User有外键关系
	def __str__(self):
		"""返回model的字符串表示"""
		return self.text

class Entry(models.Model):
	"""学到的有关某个主题的具体知识"""
	topic=models.ForeignKey(Topic)
	text = models.TextField()
	date_added=models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "entries"

	def __str__(self):
		"""返回Model的字符串表示"""
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry
class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.http import HttpResponseRedirect,Http404
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render
from .models import Topic, Entry
from .forms import TopicForm,EntryForm

# Create your views here.
def index(request):
	"""学习笔记的主页"""
	return render(request,'learning_logs/index.html')

@login_required
def topics(request):
	"""显示所有的主题"""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {"topics":topics}
	return render(request,'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
	"""显示主题下包含的详细entries"""
	topic = Topic.objects.get(id=topic_id)
	if topic.owner != request.user:
		raise Http404
	entries = topic.entry_set.order_by('-date_added')
	context = {"topic":topic,'entries':entries}
	return render(request,'learning_logs/topic.html',context)

@login_required
def new_topic(request):
	"""添加新主题"""
	if request.method != 'POST':
		form=TopicForm
	else:
		form=TopicForm(request.POST)
		if form.is_valid():
		#	form.save()
			new_topic=form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics')) #通过appname加上urls.py定义的name得到url
	context={'form':form}
	return render(request,'learning_logs/new_topic.html',context)

@login_required
def del_topic(request,topic_id):
	"""删除主题"""
	deltopic = Topic.objects.filter(owner=request.user).get(id=topic_id).delete()
	if deltopic:
		return HttpResponseRedirect(reverse('learning_logs:topics'))
	context = {"deltopic":deltopic}
	return render(request,'learning_logs/topics.html',context)


@login_required
def new_entry(request,topic_id):
	topic=Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form=EntryForm()
	else:
		form=EntryForm(request.POST)
		if form.is_valid():
			new_entry=form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return  HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
	context={"topic":topic,"form":form}
	return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
	"""实现编辑条目"""
	entry=Entry.objects.get(id=entry_id)
	topic=entry.topic
	if request.method != "POST":
		form=EntryForm(instance=entry)
	else:
		form=EntryForm(instance=entry,data=request.POST)
		if form.is_valid():
			form.save()
			return  HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))	
	context={"entry":entry,'topic':topic,"form":form}
	return render(request,'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout,login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
	
def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
	"""注册新用户"""
	if request.method != "POST":
		#显示空的注册表单
		form=UserCreationForm()
	else:
		#处理填好的表单
		form = UserCreationForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			#让用户自动登录，在重定向到主页
			authenticate_user = authenticate(username=new_user.username,password=request.POST['password1'])
			login(request,authenticate_user)
			return HttpResponseRedirect(reverse('learning_logs:index'))
	context={"form":form}
	return render(request,"users/register.html",context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width",initial-scale=1>
	</head> 
	<title>学习笔记</title>
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	<body>
		<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{%url 'learning_logs:index'%}">学习笔记</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{%url 'learning_logs:topics'%}">主题</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
			<!--如果用户完成登录,此方法是django自带的认证类方法 -->
			{%if user.is_authenticated %}
			<li><a>Hello,{{user.username}}.</a></li>
            <li class="active"><a href="{%url 'users:logout'%}">注销</a></li>
			{% else %}
            <li class="active"><a href="{%url 'users:register'%}">注册</a></li>
            <li class="active"><a href="{%url 'users:login'%}">登录</a></li>
			{%endif%}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	<div class="container">
		<!--添加header块 -->
		<div class="page-header">
			{% block header %}{% endblock header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</div>
	</body>
</html>




















<!--
<p>
	<a href="{%url 'learning_logs:index' %}">学习笔记</a>
	<a href="{%url 'learning_logs:topics' %}">学习主题</a>
	{% if user.is_authenticated%}
		您好,{{user.username}}
		<a href="{%url 'users:logout'%}">注销</a>
	{% else %}
		<a href="{%url 'users:register' %}">注册</a>-
		<a href="{%url 'users:login' %}">登录</a>
	{% endif %}
</p>
-->

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></p>
<p>编辑条目</p>
<form action="{%url 'learning_logs:edit_entry' entry.id%}" method="post">
	{% csrf_token%}
	{{form.as_p}}
	<button name='submit'>保存</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{%block header%}
	<div class="jumbotron">
		<h2>跟踪你的学习</h2>
	</div>
{% endblock header %}
{% block content %}
<h3>
<a href="{%url 'users:register' %}">注册</a>可以跟踪你的学习,可以创建任意的主题
</h3>
<p class="lead">
添加一些关于学习的主题，主题可以添加不限制的条目进行跟踪学习。
</p>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{%block header%}
<h2>添加新条目</h2>
{%endblock header%}

{% block content %}
<p><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></p>
<form action="{%url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{%buttons%}
	<button name="submit" class="btn btn-primary">提交</button>
	{%endbuttons%}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{%block header%}
	<h2>新建主题</h2>
{%endblock header%}

{% block content %}
<form action="{%url 'learning_logs:new_topic' %}" method='post' class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	{%buttons%}
		<button name="submit" class="btn btn-primary">提交</button>
	{%endbuttons%}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{%block header%}
	<h2>{{topic}}</h2>
{%endblock header%}


{% block content %}
<p>主题: {{topic}}</p>
<p>
	<a href={%url 'learning_logs:new_entry' topic.id%}>添加条目</a>
</p>
	{%for entry in  entries%}
	<div class="panel panel-default">
		<div class="panel-heading">
		<h3>
		{{entry.date_added| date:'M d,Y H:i'}}
		<small>
			<a href={%url 'learning_logs:edit_entry' entry.id%}>编辑条目</a>
		</small>
		</h3>
		</div>
		<div class="panel-body">
		<p>{{entry.text|linebreaks}}</p>
		</div>
	</div>
	{% empty %}	
		没有创建任何条目
	{%endfor%}
{% endblock content %}

learning_logs/templates/learning_logs/topic_old.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Topic{{topic}}</p>
<p>
	<a href={%url 'learning_logs:new_entry' topic.id%}>添加条目</a>
</p>
<ul>
	{%for entry in  entries%}
	<li>
		<p>{{entry.date_added| date:'M d,Y H:i'}}</p>
		<p>{{entry.text|linebreaks}}</p>
		<p>
			<a href={%url 'learning_logs:edit_entry' entry.id%}>编辑条目</a>
		</p>
	{% empty %}	
		<li>没有创建任何条目</li>
	</li>
	{%endfor%}
</ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{%load bootstrap3 %}

{%block header %}
    <h2>主题</h2>
{%endblock header%}


{% block content %}
{#<ul>#}
{#	{% for topic in topics%}#}
{#	<li>#}
{#		<h3>#}
{#		<a href="{%url 'learning_logs:topic' topic.id %}">{{topic}}</a>#}
{#            {% buttons %}#}
{#                <h4><button class="btn btn-danger"><a href={%url "learning_logs:del_topic" topic.id %}>删除</a></button></h4>#}
{#            {% endbuttons %}#}
{#		</h3>#}
{#	</li>#}
{#	{% empty %}#}
{#	<li>没有创建任何主题</li>#}
{#	{% endfor %}#}
{##}
{#</ul>#}
    <table class="table table-hover">
      <thead>
        <tr>
          <th>主题id</th>
          <th>主题名称</th>
          <th>删除选项</th>
        </tr>
      </thead>
      <tbody>
      {% for topic in topics%}
        <tr>
          <th scope="row">{{ topic.id }}</th>
          <td><a href="{%url 'learning_logs:topic' topic.id %}">{{topic}}</a></td>
          <td>
              {% buttons %}
                <h4><button class="btn btn-danger"><a href={%url "learning_logs:del_topic" topic.id %}>删除</a></button></h4>
              {% endbuttons %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

<h3><a href={%url "learning_logs:new_topic"%}>新建主题</a></h3>

{% endblock content %}

learning_logs/templates/learning_logs/topics_old.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Topics</p>
<ul>
	{% for topic in topics%}
	<li>
		<a href="{%url 'learning_logs:topic' topic.id %}">{{topic}}</a>
	</li>
	{% empty %}
	<li>没有创建任何主题</li>
	{% endfor %}
</ul>
<a href={%url "learning_logs:new_topic"%}>新建主题</a>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
	<h2>登录<h2>
{% endblock header%}

{% block content %}
	<form method="post" action="{%url 'users:login' %}" class="form">
		{%csrf_token%}
		{% bootstrap_form form %}
	{% buttons %}
	<button name="submit" class="btn btn-primary">登录</button>
	{% endbuttons %}
	<input type="hidden" name='next' value="{%url 'learning_logs:topics'%}">
	</form>

{% endblock content %}




<!--
	{% if form.errors %}
	<p>用户名和密码不匹配，请重试!</p>
	{% endif %}
	<form action="{%url 'users:login' %}" method="post">
		{%csrf_token%}
		{{form.as_p}}
	<button name='submit'>登录</button>
	<input type="hidden" name='next' value="{%url 'learning_logs:topics'%}">
	</form>
-->

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{%load bootstrap3%}
{%block header%}
<h2>注册</h2>
{%endblock header%}
{% block content %}
	<form action="{%url 'users:register' %}" method="post" class="form">
		{%csrf_token%}
		{%bootstrap_form form%}
	{%buttons%}
	<button name='submit' class="btn btn-primary">注册</button>
	{%endbuttons%}
	<input type="hidden" name='next' value="{%url 'learning_logs:index'%}">
	</form>
{% endblock content %}

users/templates/users/registerbk.html
{% extends "learning_logs/base.html" %}
{% block content %}
	<form action="{%url 'users:register' %}" method="post">
		{%csrf_token%}
		{{form.as_p}}
	<button name='submit'>注册</button>
	<input type="hidden" name='next' value="{%url 'learning_logs:index'%}">
	</form>
{% endblock content %}